import { Injectable, signal } from '@angular/core';

export type AppLanguage = 'fr' | 'en' | 'nl';

const STORAGE_KEY = 'portfolio-language';

const translations: Record<AppLanguage, Record<string, string>> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'A propos',
    'nav.contact': 'Contact',
    'language.label': 'Langue',
    'language.fr': 'Francais',
    'language.en': 'Anglais',
    'language.nl': 'Neerlandais',
    'footer.eyebrow': 'Une idee, un projet, une opportunite ?',
    'footer.title': 'Construisons une experience web qui fait la difference.',
    'footer.text': 'Echangeons autour de vos besoins et donnons une base solide a votre prochain projet.',
    'footer.cta': 'Parlons-en',
    'footer.brandRole': 'Developpeur Full-Stack',
    'footer.brandText': 'Des applications Java & Angular modernes, fiables et pensees jusque dans les details.',
    'footer.navigation': 'Navigation',
    'footer.navigationAria': 'Navigation du pied de page',
    'footer.home': 'Accueil',
    'footer.about': 'A propos',
    'footer.contact': 'Contact',
    'footer.projects': 'Projets',
    'footer.availabilityTitle': 'Disponibilite',
    'footer.availability': 'Ouvert aux opportunites web',
    'footer.rights': 'Tous droits reserves.',
    'footer.signature': 'Concu avec Angular et beaucoup de curiosite.',
    'footer.backTop': 'Retour en haut',
    'footer.homeAria': "Retour a l'accueil",
    'home.badge': 'Disponible pour une opportunite web developpeur',
    'home.subtitle': 'Developpeur Full-Stack Java & Angular',
    'home.text': 'Je concois des applications web modernes, responsives et performantes avec Angular, Spring Boot, Docker et PostgreSQL.',
    'home.projectsCta': 'Voir mes projets',
    'home.contactCta': 'Me contacter',
    'home.aboutLabel': 'A propos',
    'home.aboutTitle': 'Une presentation claire de mon profil',
    'home.aboutText': 'Cette page presente mon profil de developpeur avec une identite visuelle moderne, une stack technique clairement affichee et quelques projets concrets centres sur Java, Angular et l integration full-stack. Je me considere toujours comme un developpeur en apprentissage, a un niveau intermediaire : dans notre metier, il y a toujours de nouvelles choses a decouvrir et a maitriser. Je suis capable de concevoir, developper et maintenir des applications web securisees, evolutives et performantes. Je possede des connaissances en analyse fonctionnelle, en modelisation UML, en developpement d API REST securisees avec JWT, en gestion de bases de donnees relationnelles, en integration front-end et en tests logiciels. Serieux, polyvalent et motive, je travaille efficacement en equipe tout en respectant les objectifs et les delais d un projet.',
    'home.stackLabel': 'Stack',
    'home.stackTitle': 'Technologies principales',
    'home.projectsLabel': 'Projets',
    'home.projectsTitle': 'Quelques realisations a mettre en avant',
    'home.contactLabel': 'Contact',
    'home.contactTitle': 'Construisons quelque chose de solide',
    'home.carouselAria': 'Technologies utilisees',
    'home.emailButton': 'Envoyer un email',
    'project.managementTitle': 'Application Full-Stack de Gestion',
    'project.managementText': 'Application web moderne avec Angular, Spring Boot et base de donnees relationnelle pour gerer des utilisateurs, donnees metier et tableaux de bord.',
    'project.apiTitle': 'API Securisee Spring Boot',
    'project.apiText': 'Backend REST structure avec authentification, gestion des roles, endpoints securises et integration frontend Angular.',
    'project.dockerTitle': 'Plateforme Dockerisee',
    'project.dockerText': 'Projet conteneurise avec Docker pour simplifier le deploiement local, la configuration de l environnement et l integration de la base de donnees.',
    'about.title': 'A propos',
    'about.intro': "Voici les outils que j'utilise pour developper mes projets.",
    'about.frameworks': 'Frameworks utilises',
    'about.extraTitle': 'Savoir-faire supplementaires : Creer des solutions innovantes sans coder',
    'about.noCodeText': 'Je suis capable de creer des solutions completes avec des plateformes No Code comme Zapier, combinant design et fonctionnalite sans ecrire une seule ligne de code.',
    'about.wordpressText': 'Expert en creation de sites web avec WordPress, en combinant themes premium, plugins puissants et personnalisation avancee pour un rendu professionnel.',
    'about.aiTitle': 'IA & Strategie',
    'about.aiText': 'J utilise l Intelligence Artificielle pour des besoins strategiques, optimiser les processus et gagner du temps precieux dans la realisation de projets.',
    'contact.title': 'Parlons de votre projet',
    'contact.subtitle': "Je suis passionne par la creation de solutions innovantes. N'hesitez pas a me contacter.",
    'contact.formTitle': 'Envoyez-moi un message',
    'contact.lastName': 'Nom *',
    'contact.firstName': 'Prenom *',
    'contact.email': 'Email *',
    'contact.phone': 'Telephone',
    'contact.subject': 'Sujet',
    'contact.message': 'Message *',
    'contact.lastNamePlaceholder': 'Votre nom',
    'contact.firstNamePlaceholder': 'Votre prenom',
    'contact.emailPlaceholder': 'votre.email@example.com',
    'contact.phonePlaceholder': 'Votre numero',
    'contact.subjectPlaceholder': 'Objet du message',
    'contact.messagePlaceholder': 'Decrivez votre projet...',
    'contact.requiredLastName': 'Le nom est requis',
    'contact.requiredFirstName': 'Le prenom est requis',
    'contact.minTwo': 'Minimum 2 caracteres',
    'contact.requiredEmail': "L'email est requis",
    'contact.invalidEmail': 'Email invalide',
    'contact.requiredMessage': 'Le message est requis',
    'contact.minMessage': 'Minimum 10 caracteres',
    'contact.submit': 'Envoyer le message',
    'contact.loading': 'Envoi en cours...',
    'contact.success': 'Message envoye avec succes !',
    'contact.error': 'Une erreur est survenue. Veuillez reessayer plus tard.',
    'contact.posterAlt': 'Affiche Kangoute'
  },
  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'language.label': 'Language',
    'language.fr': 'French',
    'language.en': 'English',
    'language.nl': 'Dutch',
    'footer.eyebrow': 'An idea, a project, an opportunity?',
    'footer.title': 'Let us build a web experience that makes a difference.',
    'footer.text': 'Let us discuss your needs and give your next project a solid foundation.',
    'footer.cta': 'Let us talk',
    'footer.brandRole': 'Full-Stack Developer',
    'footer.brandText': 'Modern, reliable Java & Angular applications crafted with attention to detail.',
    'footer.navigation': 'Navigation',
    'footer.navigationAria': 'Footer navigation',
    'footer.home': 'Home',
    'footer.about': 'About',
    'footer.contact': 'Contact',
    'footer.projects': 'Projects',
    'footer.availabilityTitle': 'Availability',
    'footer.availability': 'Open to web opportunities',
    'footer.rights': 'All rights reserved.',
    'footer.signature': 'Built with Angular and a lot of curiosity.',
    'footer.backTop': 'Back to top',
    'footer.homeAria': 'Back to home',
    'home.badge': 'Available for a web developer opportunity',
    'home.subtitle': 'Java & Angular Full-Stack Developer',
    'home.text': 'I build modern, responsive and high-performance web applications with Angular, Spring Boot, Docker and PostgreSQL.',
    'home.projectsCta': 'View my projects',
    'home.contactCta': 'Contact me',
    'home.aboutLabel': 'About',
    'home.aboutTitle': 'A clear overview of my profile',
    'home.aboutText': 'This page presents my developer profile with a modern visual identity, a clear technical stack and concrete projects focused on Java, Angular and full-stack integration. I still consider myself a learning developer at an intermediate level: in our field, there are always new things to discover and master. I can design, develop and maintain secure, scalable and high-performance web applications. I also have knowledge in functional analysis, UML modeling, secure REST API development with JWT, relational databases, front-end integration and software testing. Serious, versatile and motivated, I work efficiently in teams while respecting project goals and deadlines.',
    'home.stackLabel': 'Stack',
    'home.stackTitle': 'Main technologies',
    'home.projectsLabel': 'Projects',
    'home.projectsTitle': 'Selected work to highlight',
    'home.contactLabel': 'Contact',
    'home.contactTitle': 'Let us build something solid',
    'home.carouselAria': 'Technologies used',
    'home.emailButton': 'Send an email',
    'project.managementTitle': 'Full-Stack Management Application',
    'project.managementText': 'Modern web application with Angular, Spring Boot and a relational database to manage users, business data and dashboards.',
    'project.apiTitle': 'Secure Spring Boot API',
    'project.apiText': 'Structured REST backend with authentication, role management, secured endpoints and Angular frontend integration.',
    'project.dockerTitle': 'Dockerized Platform',
    'project.dockerText': 'Containerized project with Docker to simplify local deployment, environment configuration and database integration.',
    'about.title': 'About',
    'about.intro': 'Here are the tools I use to develop my projects.',
    'about.frameworks': 'Frameworks used',
    'about.extraTitle': 'Additional expertise: creating innovative solutions without coding',
    'about.noCodeText': 'I can create complete solutions with No Code platforms such as Zapier, combining design and functionality without writing a single line of code.',
    'about.wordpressText': 'Experienced in creating websites with WordPress, combining premium themes, powerful plugins and advanced customization for a professional result.',
    'about.aiTitle': 'AI & Strategy',
    'about.aiText': 'I use Artificial Intelligence for strategic needs, process optimization and saving valuable time during project delivery.',
    'contact.title': 'Let us talk about your project',
    'contact.subtitle': 'I am passionate about creating innovative solutions. Feel free to contact me.',
    'contact.formTitle': 'Send me a message',
    'contact.lastName': 'Last name *',
    'contact.firstName': 'First name *',
    'contact.email': 'Email *',
    'contact.phone': 'Phone',
    'contact.subject': 'Subject',
    'contact.message': 'Message *',
    'contact.lastNamePlaceholder': 'Your last name',
    'contact.firstNamePlaceholder': 'Your first name',
    'contact.emailPlaceholder': 'your.email@example.com',
    'contact.phonePlaceholder': 'Your phone number',
    'contact.subjectPlaceholder': 'Message subject',
    'contact.messagePlaceholder': 'Describe your project...',
    'contact.requiredLastName': 'Last name is required',
    'contact.requiredFirstName': 'First name is required',
    'contact.minTwo': 'Minimum 2 characters',
    'contact.requiredEmail': 'Email is required',
    'contact.invalidEmail': 'Invalid email',
    'contact.requiredMessage': 'Message is required',
    'contact.minMessage': 'Minimum 10 characters',
    'contact.submit': 'Send message',
    'contact.loading': 'Sending...',
    'contact.success': 'Message sent successfully!',
    'contact.error': 'An error occurred. Please try again later.',
    'contact.posterAlt': 'Kangoute poster'
  },
  nl: {
    'nav.home': 'Start',
    'nav.about': 'Over mij',
    'nav.contact': 'Contact',
    'language.label': 'Taal',
    'language.fr': 'Frans',
    'language.en': 'Engels',
    'language.nl': 'Nederlands',
    'footer.eyebrow': 'Een idee, een project, een kans?',
    'footer.title': 'Laten we een webervaring bouwen die het verschil maakt.',
    'footer.text': 'Laten we je behoeften bespreken en je volgende project een sterke basis geven.',
    'footer.cta': 'Laten we praten',
    'footer.brandRole': 'Full-Stack Developer',
    'footer.brandText': 'Moderne en betrouwbare Java & Angular applicaties met oog voor detail.',
    'footer.navigation': 'Navigatie',
    'footer.navigationAria': 'Voettekstnavigatie',
    'footer.home': 'Start',
    'footer.about': 'Over mij',
    'footer.contact': 'Contact',
    'footer.projects': 'Projecten',
    'footer.availabilityTitle': 'Beschikbaarheid',
    'footer.availability': 'Open voor webopportuniteiten',
    'footer.rights': 'Alle rechten voorbehouden.',
    'footer.signature': 'Gemaakt met Angular en veel nieuwsgierigheid.',
    'footer.backTop': 'Terug naar boven',
    'footer.homeAria': 'Terug naar start',
    'home.badge': 'Beschikbaar voor een webdeveloper opportuniteit',
    'home.subtitle': 'Java & Angular Full-Stack Developer',
    'home.text': 'Ik bouw moderne, responsieve en performante webapplicaties met Angular, Spring Boot, Docker en PostgreSQL.',
    'home.projectsCta': 'Bekijk mijn projecten',
    'home.contactCta': 'Contacteer mij',
    'home.aboutLabel': 'Over mij',
    'home.aboutTitle': 'Een duidelijke voorstelling van mijn profiel',
    'home.aboutText': 'Deze pagina stelt mijn ontwikkelaarsprofiel voor met een moderne visuele identiteit, een duidelijke technische stack en concrete projecten rond Java, Angular en full-stack integratie. Ik beschouw mezelf nog steeds als een lerende ontwikkelaar op een gemiddeld niveau: in ons vak zijn er altijd nieuwe dingen te ontdekken en te beheersen. Ik kan veilige, schaalbare en performante webapplicaties ontwerpen, ontwikkelen en onderhouden. Ik heb ook kennis van functionele analyse, UML-modellering, beveiligde REST API ontwikkeling met JWT, relationele databases, front-end integratie en softwaretests. Serieus, veelzijdig en gemotiveerd werk ik efficient in teamverband met respect voor doelen en deadlines.',
    'home.stackLabel': 'Stack',
    'home.stackTitle': 'Belangrijkste technologieen',
    'home.projectsLabel': 'Projecten',
    'home.projectsTitle': 'Enkele realisaties om uit te lichten',
    'home.contactLabel': 'Contact',
    'home.contactTitle': 'Laten we iets solides bouwen',
    'home.carouselAria': 'Gebruikte technologieen',
    'home.emailButton': 'E-mail verzenden',
    'project.managementTitle': 'Full-Stack Beheerapplicatie',
    'project.managementText': 'Moderne webapplicatie met Angular, Spring Boot en een relationele database voor gebruikers, bedrijfsdata en dashboards.',
    'project.apiTitle': 'Beveiligde Spring Boot API',
    'project.apiText': 'Gestructureerde REST backend met authenticatie, rollenbeheer, beveiligde endpoints en Angular frontend integratie.',
    'project.dockerTitle': 'Gedockeriseerde Platform',
    'project.dockerText': 'Gecontaineriseerd project met Docker om lokale deployment, omgevingsconfiguratie en database-integratie te vereenvoudigen.',
    'about.title': 'Over mij',
    'about.intro': 'Dit zijn de tools die ik gebruik om mijn projecten te ontwikkelen.',
    'about.frameworks': 'Gebruikte frameworks',
    'about.extraTitle': 'Extra expertise: innovatieve oplossingen maken zonder code',
    'about.noCodeText': 'Ik kan complete oplossingen maken met No Code platformen zoals Zapier, waarbij design en functionaliteit samenkomen zonder een regel code te schrijven.',
    'about.wordpressText': 'Ervaren in het maken van websites met WordPress, met premium thema s, krachtige plugins en geavanceerde personalisatie voor een professioneel resultaat.',
    'about.aiTitle': 'AI & Strategie',
    'about.aiText': 'Ik gebruik Artificiele Intelligentie voor strategische noden, procesoptimalisatie en tijdwinst bij de uitvoering van projecten.',
    'contact.title': 'Laten we praten over je project',
    'contact.subtitle': 'Ik ben gepassioneerd door het maken van innovatieve oplossingen. Neem gerust contact op.',
    'contact.formTitle': 'Stuur mij een bericht',
    'contact.lastName': 'Naam *',
    'contact.firstName': 'Voornaam *',
    'contact.email': 'E-mail *',
    'contact.phone': 'Telefoon',
    'contact.subject': 'Onderwerp',
    'contact.message': 'Bericht *',
    'contact.lastNamePlaceholder': 'Je naam',
    'contact.firstNamePlaceholder': 'Je voornaam',
    'contact.emailPlaceholder': 'jouw.email@example.com',
    'contact.phonePlaceholder': 'Je nummer',
    'contact.subjectPlaceholder': 'Onderwerp van het bericht',
    'contact.messagePlaceholder': 'Beschrijf je project...',
    'contact.requiredLastName': 'Naam is verplicht',
    'contact.requiredFirstName': 'Voornaam is verplicht',
    'contact.minTwo': 'Minimum 2 tekens',
    'contact.requiredEmail': 'E-mail is verplicht',
    'contact.invalidEmail': 'Ongeldige e-mail',
    'contact.requiredMessage': 'Bericht is verplicht',
    'contact.minMessage': 'Minimum 10 tekens',
    'contact.submit': 'Bericht verzenden',
    'contact.loading': 'Bezig met verzenden...',
    'contact.success': 'Bericht succesvol verzonden!',
    'contact.error': 'Er is een fout opgetreden. Probeer het later opnieuw.',
    'contact.posterAlt': 'Kangoute affiche'
  }
};

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly languages: AppLanguage[] = ['fr', 'en', 'nl'];
  readonly currentLanguage = signal<AppLanguage>(this.getInitialLanguage());

  constructor() {
    this.updateDocumentLanguage(this.currentLanguage());
  }

  setLanguage(language: AppLanguage): void {
    this.currentLanguage.set(language);

    if (typeof localStorage !== 'undefined') {
      localStorage.setItem(STORAGE_KEY, language);
    }

    this.updateDocumentLanguage(language);
  }

  translate(key: string): string {
    return translations[this.currentLanguage()][key] ?? translations.fr[key];
  }

  private getInitialLanguage(): AppLanguage {
    if (typeof localStorage === 'undefined') {
      return 'fr';
    }

    const savedLanguage = localStorage.getItem(STORAGE_KEY);
    return this.isSupportedLanguage(savedLanguage) ? savedLanguage : 'fr';
  }

  private isSupportedLanguage(language: string | null): language is AppLanguage {
    return language === 'fr' || language === 'en' || language === 'nl';
  }

  private updateDocumentLanguage(language: AppLanguage): void {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language;
    }
  }
}
